### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by richtercamden** [rarcega/instagram-scraper#134] opened 2017-12-02 00:19 UTC
I noticed that it wouldn't scrape anymore when running (all the users are private), and after further investigation, after launching it immediately says "ERROR: Login failed for camden_richter". I've tried upgrading with pip, I've tried resetting my instagram password, and I double checked that the settings in the file were correct. Still doesn't work.

**Comment by willshion** [comment] 2017-12-08 08:42
ERROR: {"status": "ok", "user": true, "authenticated": false}

**Comment by clublek** [comment] 2017-12-08 09:35
Yes, it's broken now. Get the login failed error as well, when trying to download stories.

**Comment by jochensiegler** [comment] 2017-12-09 08:55
same her got the message:
ERROR: Login failed for stumpmrudi1982
ERROR: Please verify your account at /challenge/273403908/5g2r1hWQqM/
and on my smartphone i also got a site to verfify. But if i do this and try again with the scraper i got the same message with another link

**Comment by durble** [comment] 2017-12-09 22:51
It appears that Instagram changed the login mechanism on their end recently. Logging in with the scraper now triggers a security challenge. Manually going through the challenge does not fix the issue either.

**Comment by vanyasem** [comment] 2017-12-12 21:58
I could not fix it, but instead was able to request a challenge within the script, and it works for one session. It seems like I get a challenge even when I login with my usual web browser, so it's either that the account is flagged, or Instagram introduced mandatory challenges for web logins.

**Comment by vanyasem** [comment] 2017-12-12 21:59
PR with these changes is coming soon ;)

**Comment by orbancedric** [comment] 2017-12-14 16:13
I managed to log in successfully multiple times in a row again. However, logging in multiple times within a short time span seemed to trigger the issue again, and I'm now locked out. Maybe a solution here is to save the session cookies and re-use them?

**Comment by vanyasem** [comment] 2017-12-17 21:50
@richtercamden please close this issue now. It's not a bug in Instagram Scraper, as Instagram haven't changed their login method in any way. It's just that your account got flagged. My PR that allows interactive login challenges was accepted.

@willshion your error is completely unrelated, it means that your password is wrong. Don't forget to escape it (or put it in quotes `"`) if it has special characters in it.

**Closed** 2017-12-17 22:32 UTC
