### ISSUE TITLE
Progress bar is blank on users with over 1,500 posts

### ISSUE THREAD

**Issue by Rich700000000000** [rarcega/instagram-scraper#3] opened 2016-06-07 02:45 UTC
So I've used around 7 times over the past few days, and this is what I've noticed. While all the images download fine, if the user has around 1,500 posts or more the progress bar is blank, and  it gives an error when it ends:

    Downloading:   0%|                                                                                                                         | 0/2460 [00:00<?, ?it/s]    
    Traceback (most recent call last):
      File "app.py", line 59, in <module>
        print ('%r generated an exception: %s') % (item['url'], future.exception())
    KeyError: 'url'

What do you think could be causing that?

**Comment by rarcega** [comment] 2016-06-16 02:45
I tried to replicate this behavior with users who have > 1500 posts (e.g. justinbieber with > 5000 posts), but was unsuccessful. If possible, can you provide a user that I can reproduce this with?

As a side note, I noticed that for a large number of posts, the app waited until all posts were crawled before starting to download the media. I've changed the behavior to download as posts are found. This effectively renders the progress meter moot as downloading outpaces the crawling--so by the time the meter is shown (which requires the total # of media items) everything has already been downloaded.

**Comment by rarcega** [comment] 2016-06-25 02:39
Every post should have a url with the location of the media whether it be an image or video. Looks like the url is not being set for a reason. As a result, the print statement in the exception handler was erroring out which effectively hid the exception reason. I've changed the print statement so the actual exception should now be shown. Can you try to replicate?

**Comment by Rich700000000000** [comment] 2016-06-25 04:30
You mean this:

	Downloading:   0%|                                                                                                                          | 0/333 [00:00<?, ?it/s]
	Traceback (most recent call last):
  	  File "app4.py", line 71, in <module>
    	     print ('%r generated an exception: %s') % (item['url'], future.exception())
	KeyError: 'url'


Yeah, this keeps happening. I don't know why.

**Comment by rarcega** [comment] 2016-06-28 01:16
Can you update to the latest code and let me know the error?

**Comment by rarcega** [comment] 2016-06-30 00:37
Fixed in f9eef80a9213cee0bfe107aada5797364f1222a4

**Closed by rarcega** 2016-06-30 00:37 UTC
Labels: bug
