### ISSUE TITLE
url keyerror happening randomly 

### ISSUE THREAD

**Issue by Karlheinzniebuhr** [rarcega/instagram-scraper#6] opened 2016-06-24 21:33 UTC
`Downloading:   0%|                                                                                                                                         | 0/432 [00:00<?, ?it/s]Traceback (most recent call last):
  File "app.py", line 71, in <module>
    print ('%r generated an exception: %s') % (item['url'], future.exception())
KeyError: 'url'`

**Comment by rarcega** [comment] 2016-06-25 02:32
Duplicate of #3

**Closed by rarcega** 2016-06-25 02:32 UTC
Labels: duplicate

**Comment by Rich700000000000** [comment] 2016-06-25 04:25
Yeah, this keeps happening randomly.

**Comment by rarcega** [comment] 2016-06-30 00:37
Fixed in f9eef80a9213cee0bfe107aada5797364f1222a4
